table fm
    name fm
    description "table for beneficiary data"
    column id
        type string
        sql id
    column age
        type int
        sql age
    column gender
        type string
        sql gender
    column pregnancy_status
        type string
        sql pregnancy_status
    column marital_status
        type string
        sql marital_status
    column bocw_card_registration_date
        type date
        sql bocw_card_registration_date
    column health_status
        type string
        sql health_status
    column number_of_children
        type int
        sql number_of_children
    column children_school_or_college
        type string
        sql children_school_or_college
    column spouse_alive
        type bool
        sql spouse_alive
    column occupation_of_surviving_spouse
        type string
        sql occupation_of_surviving_spouse
    column spouse_occupation // <---- This column name is used in the scheme criteria
        type string
        sql occupation_of_surviving_spouse
    column receiving_pension
        type bool
        sql receiving_pension
    column receiving_government_aid
        type bool
        sql receiving_government_aid
    column home_ownership_status
        type string
        sql home_ownership_status